In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set_style('white')
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df= pd.read_csv('/Indian Liver Patient Dataset (ILPD).csv')
df.describe()

age  tot_bilirubin  direct_bilirubin  tot_proteins      albumin  \
count  583.000000     583.000000        583.000000    583.000000   583.000000   
mean    44.746141       3.298799          1.486106    290.576329    80.713551   
std     16.189833       6.209522          2.808498    242.937989   182.620356   
min      4.000000       0.400000          0.100000     63.000000    10.000000   
25%     33.000000       0.800000          0.200000    175.500000    23.000000   
50%     45.000000       1.000000          0.300000    208.000000    35.000000   
75%     58.000000       2.600000          1.300000    298.000000    60.500000   
max     90.000000      75.000000         19.700000   2110.000000  2000.000000   

          ag_ratio        sgpt        sgot     alkphos  is_patient  
count   583.000000  583.000000  583.000000  579.000000  583.000000  
mean    109.910806    6.483190    3.141852    0.947064    1.286449  
std     288.918529    1.085451    0.795519    0.319592    0.452490  
min      10.000000    2.700000    0.900000    0.300000    1.000000  
25%      25.000000    5.800000    2.600000    0.700000    1.000000  
50%      42.000000    6.600000    3.100000    0.930000    1.000000  
75%      87.000000    7.200000    3.800000    1.100000    2.000000  
max    4929.000000    9.600000    5.500000    2.800000    2.000000

In [ ]:
print(df.columns)
print('*'*50)
for i in df.columns :
    print(i)
    print(df[i].describe())
    print('*'*50)

Index(['age', 'gender', 'tot_bilirubin', 'direct_bilirubin', 'tot_proteins',
       'albumin', 'ag_ratio', 'sgpt', 'sgot', 'alkphos', 'is_patient'],
      dtype='object')
**************************************************
age
count    583.000000
mean      44.746141
std       16.189833
min        4.000000
25%       33.000000
50%       45.000000
75%       58.000000
max       90.000000
Name: age, dtype: float64
**************************************************
gender
count      583
unique       2
top       Male
freq       441
Name: gender, dtype: object
**************************************************
tot_bilirubin
count    583.000000
mean       3.298799
std        6.209522
min        0.400000
25%        0.800000
50%        1.000000
75%        2.600000
max       75.000000
Name: tot_bilirubin, dtype: float64
**************************************************
direct_bilirubin
count    583.000000
mean       1.486106
std        2.808498
min        0.100000
25%        0.200000
50%        0.

In [ ]:
df[df['alkphos'].isnull()]

age  gender  tot_bilirubin  direct_bilirubin  tot_proteins  albumin  \
209   45  Female            0.9               0.3           189       23   
241   51    Male            0.8               0.2           230       24   
253   35  Female            0.6               0.2           180       12   
312   27    Male            1.3               0.6           106       25   

     ag_ratio  sgpt  sgot  alkphos  is_patient  
209        33   6.6   3.9      NaN           1  
241        46   6.5   3.1      NaN           1  
253        15   5.2   2.7      NaN           2  
312        54   8.5   4.8      NaN           2

In [ ]:
mean=df['alkphos'].mean()

In [ ]:
df['alkphos'].fillna(value=mean, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               583 non-null    int64  
 1   gender            583 non-null    object 
 2   tot_bilirubin     583 non-null    float64
 3   direct_bilirubin  583 non-null    float64
 4   tot_proteins      583 non-null    int64  
 5   albumin           583 non-null    int64  
 6   ag_ratio          583 non-null    int64  
 7   sgpt              583 non-null    float64
 8   sgot              583 non-null    float64
 9   alkphos           583 non-null    float64
 10  is_patient        583 non-null    int64  
dtypes: float64(5), int64(5), object(1)
memory usage: 50.2+ KB


In [ ]:
df =  df.rename(columns={'tot_proteins':'Alkaline_Phosphotase','albumin':'Alanine_Aminotransferase','ag_ratio':'Aspartate_Aminotransferase','sgpt':'Total_Protiens','sgot':'Albumin','alkphos':'Albumin_and_Globulin_Ratio'}, inplace=False)
df

age  gender  tot_bilirubin  direct_bilirubin  Alkaline_Phosphotase  \
0     65  Female            0.7               0.1                   187   
1     62    Male           10.9               5.5                   699   
2     62    Male            7.3               4.1                   490   
3     58    Male            1.0               0.4                   182   
4     72    Male            3.9               2.0                   195   
..   ...     ...            ...               ...                   ...   
578   60    Male            0.5               0.1                   500   
579   40    Male            0.6               0.1                    98   
580   52    Male            0.8               0.2                   245   
581   31    Male            1.3               0.5                   184   
582   38    Male            1.0               0.3                   216   

     Alanine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  is_patient  
0        3.3                        0.90           1  
1        3.2                        0.74           1  
2        3.3                        0.89           1  
3        3.4                        1.00           1  
4        2.4                        0.40           1  
..       ...                         ...         ...  
578      1.6                        0.37           2  
579      3.2                        1.10           1  
580      3.2                        1.00           1  
581      3.4                        1.00           1  
582      4.4                        1.50           2  

[583 rows x 11 columns]

In [ ]:
df['is_patient']=df['is_patient'].replace(2,0)
df

age  gender  tot_bilirubin  direct_bilirubin  Alkaline_Phosphotase  \
0     65  Female            0.7               0.1                   187   
1     62    Male           10.9               5.5                   699   
2     62    Male            7.3               4.1                   490   
3     58    Male            1.0               0.4                   182   
4     72    Male            3.9               2.0                   195   
..   ...     ...            ...               ...                   ...   
578   60    Male            0.5               0.1                   500   
579   40    Male            0.6               0.1                    98   
580   52    Male            0.8               0.2                   245   
581   31    Male            1.3               0.5                   184   
582   38    Male            1.0               0.3                   216   

     Alanine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  is_patient  
0        3.3                        0.90           1  
1        3.2                        0.74           1  
2        3.3                        0.89           1  
3        3.4                        1.00           1  
4        2.4                        0.40           1  
..       ...                         ...         ...  
578      1.6                        0.37           0  
579      3.2                        1.10           1  
580      3.2                        1.00           1  
581      3.4                        1.00           1  
582      4.4                        1.50           0  

[583 rows x 11 columns]

In [ ]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
df['gender']=le.fit_transform(df.gender.values)
df

age  gender  tot_bilirubin  direct_bilirubin  Alkaline_Phosphotase  \
0     65       0            0.7               0.1                   187   
1     62       1           10.9               5.5                   699   
2     62       1            7.3               4.1                   490   
3     58       1            1.0               0.4                   182   
4     72       1            3.9               2.0                   195   
..   ...     ...            ...               ...                   ...   
578   60       1            0.5               0.1                   500   
579   40       1            0.6               0.1                    98   
580   52       1            0.8               0.2                   245   
581   31       1            1.3               0.5                   184   
582   38       1            1.0               0.3                   216   

     Alanine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                          16                          18             6.8   
1                          64                         100             7.5   
2                          60                          68             7.0   
3                          14                          20             6.8   
4                          27                          59             7.3   
..                        ...                         ...             ...   
578                        20                          34             5.9   
579                        35                          31             6.0   
580                        48                          49             6.4   
581                        29                          32             6.8   
582                        21                          24             7.3   

     Albumin  Albumin_and_Globulin_Ratio  is_patient  
0        3.3                        0.90           1  
1        3.2                        0.74           1  
2        3.3                        0.89           1  
3        3.4                        1.00           1  
4        2.4                        0.40           1  
..       ...                         ...         ...  
578      1.6                        0.37           0  
579      3.2                        1.10           1  
580      3.2                        1.00           1  
581      3.4                        1.00           1  
582      4.4                        1.50           0  

[583 rows x 11 columns]

In [ ]:
print ('Total Unhealthy Livers :  {} and its percentage is {} %'.format(df.is_patient.value_counts()[1], round(df.is_patient.value_counts()[1]/df.is_patient.value_counts().sum()*100,2)) )
print ('Total Healthy Livers :  {} and its percentage is {} %'.format(df.is_patient.value_counts()[0], round(df.is_patient.value_counts()[0]/df.is_patient.value_counts().sum()*100,2)) )

Total Unhealthy Livers :  416 and its percentage is 71.36 %
Total Healthy Livers :  167 and its percentage is 28.64 %


In [ ]:
X = df[['age','gender' ,'tot_bilirubin',
        'direct_bilirubin',
        'Alkaline_Phosphotase',
        'Alanine_Aminotransferase', 'Aspartate_Aminotransferase',
       'Total_Protiens', 'Albumin', 'Albumin_and_Globulin_Ratio']]
y=df[['is_patient']]


In [ ]:
from sklearn import preprocessing

from sklearn.model_selection import train_test_split
from sklearn import model_selection
X_scaler = preprocessing.normalize(X)

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,shuffle=True)
print(X_train)
print(X_test)
print(y_train)
print(y_test)
print("Train Shape: {}".format(X_train.shape))
print("Test Shape: {}".format(X_test.shape))


     age  gender  tot_bilirubin  direct_bilirubin  Alkaline_Phosphotase  \
77    68       0            0.6               0.1                  1620   
581   31       1            1.3               0.5                   184   
210   28       1            0.8               0.3                   190   
192   60       1            2.3               0.6                   272   
449   48       0            0.9               0.2                   173   
..   ...     ...            ...               ...                   ...   
71    75       0            0.8               0.2                   188   
106   36       1            5.3               2.3                   145   
270   37       1            0.7               0.2                   235   
435   17       0            0.5               0.1                   206   
102   17       1            0.9               0.2                   224   

     Alanine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
77                    

Logistic regression


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report , accuracy_score , confusion_matrix
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [ ]:
score=lr.score(X_test,y_test)
print("Accuracy score - ", metrics.accuracy_score(y_test,y_pred))
print("Classification of the model is ")
print(metrics.classification_report(y_test, y_pred, digits=3))

result = confusion_matrix(y_test, y_pred)
print("Confusion matrix is \n",result)


Accuracy score -  0.7435897435897436
Classification of the model is 
              precision    recall  f1-score   support

           0      0.500     0.133     0.211        30
           1      0.761     0.954     0.847        87

    accuracy                          0.744       117
   macro avg      0.631     0.544     0.529       117
weighted avg      0.694     0.744     0.684       117

Confusion matrix is 
 [[ 4 26]
 [ 4 83]]


Logistic regression grid search


In [ ]:
from sklearn.model_selection import GridSearchCV
clf = LogisticRegression()
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values,scoring = 'recall')
grid_clf_acc.fit(X_train, y_train)



#Predict values based on new parameters
y_pred_acc = grid_clf_acc.predict(X_test)

# New Model Evaluation metrics
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_acc)))
print(metrics.classification_report(y_test, y_pred_acc, digits=3))



#Logistic Regression (Grid Search) Confusion matrix
confusion_matrix(y_test,y_pred_acc)

Accuracy Score : 0.7606837606837606
              precision    recall  f1-score   support

           0      0.600     0.200     0.300        30
           1      0.776     0.954     0.856        87

    accuracy                          0.761       117
   macro avg      0.688     0.577     0.578       117
weighted avg      0.731     0.761     0.713       117



array([[ 6, 24],
       [ 4, 83]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=80, max_depth=8, random_state=0)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)

In [ ]:
accuracy_rf = accuracy_score(y_pred, y_test)
print("Accuracy score is ",accuracy_rf)
result1 =classification_report(y_pred, y_test)
print("Classification report is\n",result1)
result = confusion_matrix(y_test, y_pred)
print("Confusion matrix is \n",result)

Accuracy score is  0.7692307692307693
Classification report is
               precision    recall  f1-score   support

           0       0.43      0.57      0.49        23
           1       0.89      0.82      0.85        94

    accuracy                           0.77       117
   macro avg       0.66      0.69      0.67       117
weighted avg       0.80      0.77      0.78       117

Confusion matrix is 
 [[13 17]
 [10 77]]


Random Forest Grid Search


In [ ]:
param_grid = {
    'bootstrap': [True],
    'max_depth': [5, 80, 90, 100],
    'max_features': [2,3],
    'min_samples_leaf': [3,5],
    'min_samples_split': [8,9],
    'n_estimators': [100, 200,300],
    'random_state': [21,42,10,5]
}

In [ ]:
rf = RandomForestClassifier()
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, cv = 3, n_jobs = -1, verbose = 2)
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)
print(grid_search.best_score_)
y_pred_grid = grid_search.predict(X_test)

result = confusion_matrix(y_pred_grid, y_test)
print("Confusion matrix is \n",result)
accuracy_grid_search = accuracy_score(y_pred_grid, y_test)
print("Accuracy score is ", accuracy_grid_search)
print(metrics.classification_report(y_test, y_pred_grid, digits=3))


Fitting 3 folds for each of 384 candidates, totalling 1152 fits
{'bootstrap': True, 'max_depth': 80, 'max_features': 2, 'min_samples_leaf': 3, 'min_samples_split': 8, 'n_estimators': 100, 'random_state': 21}
0.7039702233250621
Confusion matrix is 
 [[10 10]
 [20 77]]
Accuracy score is  0.7435897435897436
              precision    recall  f1-score   support

           0      0.500     0.333     0.400        30
           1      0.794     0.885     0.837        87

    accuracy                          0.744       117
   macro avg      0.647     0.609     0.618       117
weighted avg      0.718     0.744     0.725       117



Support Vector Machine


In [ ]:
from sklearn.svm import SVC
svm = SVC(kernel= 'rbf',C=1, random_state =  0, gamma=0.5)
svm.fit(X_train,y_train)
y_pred_svm=svm.predict(X_test)


In [ ]:
accuracy_svm = accuracy_score(y_pred_svm, y_test)
print("Accuracy score is ",accuracy_svm)
result=classification_report(y_pred_svm, y_test)
print("Classification report is\n",result)

result1 = confusion_matrix(y_test, y_pred_svm)
print("Confusion matrix is \n",result1)

Accuracy score is  0.7435897435897436
Classification report is
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.74      0.85       117

    accuracy                           0.74       117
   macro avg       0.50      0.37      0.43       117
weighted avg       1.00      0.74      0.85       117

Confusion matrix is 
 [[ 0 30]
 [ 0 87]]


SVM GridSearch


In [ ]:
param_grid = {'C': [0.1, 1, 10, 100, 1000],
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']}
rf=SVC()

grid_svm= GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)

grid_svm.fit(X_train,y_train)





Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.702 total time=   0.0s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.699 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.702 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.710 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.699 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.702 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [ ]:
print(grid_svm.best_params_)
print(grid_svm.best_score_)
y_pred_svm = grid_svm.predict(X_test)
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_svm)))
print(metrics.classification_report(y_test, y_pred_svm, digits=3))
result = confusion_matrix(y_test, y_pred_svm)
print("Confusion matrix is \n",result)



{'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}
0.7295355753832077
Accuracy Score : 0.7264957264957265
              precision    recall  f1-score   support

           0      0.417     0.167     0.238        30
           1      0.762     0.920     0.833        87

    accuracy                          0.726       117
   macro avg      0.589     0.543     0.536       117
weighted avg      0.673     0.726     0.681       117

Confusion matrix is 
 [[ 5 25]
 [ 7 80]]


knn

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
for n in range(1,10):
  classifier1 = KNeighborsClassifier(n_neighbors= n)
  classifier1.fit(X_train,y_train)
  y_pred_knn = classifier1.predict(X_test)




In [ ]:
score = classifier1.score(X_test, y_test)
print("Score of the model is - ",score)
print("Report card of this model - ")
print(metrics.classification_report(y_test, y_pred_knn, digits=3))
print("Accuracy score - ", metrics.accuracy_score(y_test,y_pred_knn))
result = confusion_matrix(y_test, y_pred_knn)
print("Confusion matrix is \n",result)

Score of the model is -  0.7521367521367521
Report card of this model - 
              precision    recall  f1-score   support

           0      0.522     0.400     0.453        30
           1      0.809     0.874     0.840        87

    accuracy                          0.752       117
   macro avg      0.665     0.637     0.646       117
weighted avg      0.735     0.752     0.741       117

Accuracy score -  0.7521367521367521
Confusion matrix is 
 [[12 18]
 [11 76]]


knn Grid


In [ ]:
knn=KNeighborsClassifier()
k_range = list(range(1, 31))
param_grid = dict(n_neighbors=k_range)
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy', return_train_score=False,verbose=1)
grid_searchs=grid.fit(X_train, y_train)
y_pred_grid = grid_searchs.predict(X_test)

Fitting 10 folds for each of 30 candidates, totalling 300 fits


In [ ]:
print(grid_searchs.best_params_)
print(grid_searchs.best_score_)
y_pred_grid = grid_searchs.predict(X_test)
print('Accuracy Score : ' + str(accuracy_score(y_test,y_pred_grid)))
print(metrics.classification_report(y_test, y_pred_grid ,digits=3))
result = confusion_matrix(y_test, y_pred_grid)
print("Confusion matrix is \n",result)

{'n_neighbors': 23}
0.6889916743755782
Accuracy Score : 0.6837606837606838
              precision    recall  f1-score   support

           0      0.333     0.233     0.275        30
           1      0.760     0.839     0.798        87

    accuracy                          0.684       117
   macro avg      0.547     0.536     0.536       117
weighted avg      0.651     0.684     0.664       117

Confusion matrix is 
 [[ 7 23]
 [14 73]]


Naive Bayes


In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred_nb = nb.predict(X_test)

In [ ]:
score = nb.score(X_test, y_test)
print("Score of the model is - ",score)
print("Report card of this model - ")
print(metrics.classification_report(y_test, y_pred_nb, digits=3))
print("Accuracy score - ", metrics.accuracy_score(y_test,y_pred_nb))
result = confusion_matrix(y_test, y_pred_nb)
print("Confusion matrix is \n",result)

Score of the model is -  0.5128205128205128
Report card of this model - 
              precision    recall  f1-score   support

           0      0.345     1.000     0.513        30
           1      1.000     0.345     0.513        87

    accuracy                          0.513       117
   macro avg      0.672     0.672     0.513       117
weighted avg      0.832     0.513     0.513       117

Accuracy score -  0.5128205128205128
Confusion matrix is 
 [[30  0]
 [57 30]]
